@startuml

' ############# Таблицы #############

entity "Сотрудник" {
  + id: UUID [PK]
  --
  ФИО: String
  Должность: String
  Проектная команда: String
  Лимит отпускных дней: Integer
}

entity "Запрос" {
  + id: UUID [PK]
  --
  Сотрудник_id: UUID [FK]
  Дата начала: Date
  Дата окончания: Date
  Статус: String
  Руководитель_id: UUID [FK]
  Заказчик_id: UUID [FK]
}

entity "Руководитель" {
  + id: UUID [PK]
  --
  ФИО: String
  Проектная команда: String
}

entity "Заказчик" {
  + id: UUID [PK]
  --
  ФИО: String
  Проектная команда: String
}

entity "Отпуск" {
  + id: UUID [PK]
  --
  Сотрудник_id: UUID [FK]
  Дата начала: Date
  Дата окончания: Date
  Статус: String
  Проектная команда: String
  Запрос_id: UUID [FK]
  Начисление отпускных: Boolean
}

entity "Уведомление" {
  + id: UUID [PK]
  --
  Сотрудник_id: UUID [FK]
  Текст: String
  Ссылка: URL
  Статус: String
  ОфисМенеджер_id: UUID [FK]
}

entity "ОфисМенеджер" {
  + id: UUID [PK]
  --
  ФИО: String
  Проектная команда: String
}

entity "Подтверждение" {
  + id: UUID [PK]
  --
  Сотрудник_id: UUID [FK]
  Отпуск_id: UUID [FK]
  Статус: String
  Проектная команда: String
}

entity "Начисление" {
  + id: UUID [PK]
  --
  Сотрудник_id: UUID [FK]
  Отпуск_id: UUID [FK]
  Статус: String
  Проектная команда: String
}

' ############# Связи #############

Сотрудник ||--o{ Запрос : "имеет"
Руководитель ||--o{ Запрос : "согласовывает"
Заказчик ||--o{ Запрос : "согласовывает"
Запрос ||--o{ Отпуск : "создает"
Отпуск ||--o{ Уведомление : "генерирует"
ОфисМенеджер ||--o{ Уведомление : "отправляет"
Отпуск ||--o{ Подтверждение : "требует"
Отпуск ||--o{ Начисление : "инициирует"

@enduml