# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protos/calendars.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Protos/calendars.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16Protos/calendars.proto\x12\rWorkCalendars\"K\n\x12GetHolidaysRequest\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\'\n\x07\x63ountry\x18\x02 \x01(\x0e\x32\x16.WorkCalendars.Country\":\n\x10HolidaysResponse\x12\x10\n\x08holidays\x18\x01 \x03(\t\x12\x14\n\x0cpre_holidays\x18\x02 \x03(\t*\x19\n\x07\x43ountry\x12\x06\n\x02RU\x10\x00\x12\x06\n\x02ME\x10\x01\x32\x65\n\x10HolidaysProvider\x12Q\n\x0bGetHolidays\x12!.WorkCalendars.GetHolidaysRequest\x1a\x1f.WorkCalendars.HolidaysResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.calendars_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COUNTRY']._serialized_start=178
  _globals['_COUNTRY']._serialized_end=203
  _globals['_GETHOLIDAYSREQUEST']._serialized_start=41
  _globals['_GETHOLIDAYSREQUEST']._serialized_end=116
  _globals['_HOLIDAYSRESPONSE']._serialized_start=118
  _globals['_HOLIDAYSRESPONSE']._serialized_end=176
  _globals['_HOLIDAYSPROVIDER']._serialized_start=205
  _globals['_HOLIDAYSPROVIDER']._serialized_end=306
# @@protoc_insertion_point(module_scope)
